# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('tel', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('sex', models.IntegerField(null=True)),
                ('birthday', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('locate', models.CharField(max_length=50, null=True)),
                ('remark', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('create_date',models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'user_info_detail',
            },
        ),
    ]
